### ISSUE TITLE
network error

### ISSUE THREAD

**Issue by perkelpit** [Nogg-aholic/PowerSuit#1]
Greetings,

we got network errors while using your mod in multiplayer.

the weird thing is: it worked yesterday for roughly 2 hours very fine - flown and hovering around with your suit.
But since then and remaining until now the client (me) always lost connection after a few minutes.

What we did:
try without mods -> no more connection lost.
re-added only PowerSuit (was our suspect) -> loss of connection re-appeared.

here are the parts of our log-files where the problem seems to start:

client: https://pastebin.com/gUFUavxn
host: https://pastebin.com/QTf5qbXN

i hope this helps.

with best regards

**Comment by Nogg-aholic** [comment]
Hey, a potential fix was deployed with Version 0.2.0.
I havent heard of any Crashes in the Time between 0.2.0 and the now released 0.3.0 Version, so hopefully the Issue was resolved.
Please reopen this Issue if you still encounter this Crash again.
