### ISSUE TITLE
When on a tractor, the character texture is the default one instead of the power suit.

### ISSUE THREAD

**Issue by grokkingit** [Nogg-aholic/PowerSuit#10]
Satisfactory: CL139698
Power Suit: 0.4.2

I've only unlocked the biofuel power suit so far so haven't tested the others. The green character texture is there in first person and hyper tube views, but when driving the tractor the character still has the default khaki colour.

**Comment by budak7273** [comment]
Thanks for the report. The player displayed in the vehicle is no longer the same 'player' wearing a suit. It would probably be possible to also change its appearance, but this is low priority for now.

**Comment by budak7273** [comment]
Fixed in 1.0.0
