### ISSUE TITLE
horisontal bugg

### ISSUE THREAD

**Issue by davidsdata** [Nogg-aholic/PowerSuit#12]
i have power suit mk2 with blade runners, jetpack (vanilla copy) fuel cell and mid air refueling. but the suit start to hover by itself sometime. i dont know why or how. it is really annoying. 
al i want is to jump from one machine to the other not hover past everything and have to jump back, risking the same hover bugg again

**Comment by budak7273** [comment]
Closing this issue as it was resolved by the SML3 update, which changed all flight to use the base game's Hoverpack flight system, replacing the previous flight system entirely.
