### ISSUE TITLE
The UI for the Suit.

### ISSUE THREAD

**Issue by Trtimwand26** [Nogg-aholic/PowerSuit#13]
It seems the the suits UI on the screen is overlapping. Is there a way to fix it?
![image](https://user-images.githubusercontent.com/77465457/104830294-8578a580-584b-11eb-9a5d-3d8da9e68074.png)

**Comment by gkuba** [comment]
Same issue here. Its fine if you don't have anything in your hand but as soon as you equip something and it bumps up the card with the suit on it to display the weapon / item info in your hand. This is super annoying.

**Comment by simon-horny** [comment]
Do you happen to have a 2K (or more) monitor?

**Comment by simon-horny** [comment]
It also got fixed right now, lol.

**Comment by budak7273** [comment]
Closing this issue as it was fixed in the update to SML3, since we now directly modify the base game's equipment hud widget.
