### ISSUE TITLE
Turbo Fuel is not shown as being used for Clients

### ISSUE THREAD

**Issue by LooSik** [Nogg-aholic/PowerSuit#15]
In multiplayer game, clients don't see their turbo fuel amount ( normal fuel works fine ).
For host everything seems to be all right.

![obraz](https://user-images.githubusercontent.com/1782175/109428326-effa3500-79f6-11eb-93c7-089c1a3e64b6.png)

**Comment by budak7273** [comment]
Closing this issue as it was fixed in the update to SML3, and is also now managed by PowerSuit Modules instead.
