### ISSUE TITLE
Module Delete on death

### ISSUE THREAD

**Issue by deadspidervenom** [Nogg-aholic/PowerSuit#16]
Sometimes when you die all equipped module disappear.

I think, it is related to the blade runner module and dying by falling, cause that seems to be the only time i lose them.

**Comment by Nogg-aholic** [comment]
This is a somewhat known Bug. Unfortunatly this Mod is not really interacting with the Inventory aside from binding to AddItem and RemoveItem. In General , the Suit or any Equipment is an Actor in World. The Actor persists if the Item is equipped or not equipped so the players Death should hardly influrence it at all. My Guess :  The Suits Descriptor with the Pointer to the World Actor ( Suit Blueprint ) is moved into the Chest and for some reason in rare Situations the Pointer on this moved Descriptor is changed, lost or something else. the new Suit will be basically a new Actor, with a new Inventory and the old one is lost and probably GCed. I dont know how to fix this really except for some hacky workaround. I was hoping so far that CSS would fix this issue.

**Comment by budak7273** [comment]
Closing this issue as it was fixed in the update to SML3. It was related to the fact that the owner of the suit actor was the player pawn (which actually gets deleted on death) and not the player controller (which persists).
