### ISSUE TITLE
cant uninstall

### ISSUE THREAD

**Issue by Mupetz11** [Nogg-aholic/PowerSuit#17]
i cant uninstall the mod or my savegame crashes every time, wats the propper way?

**Comment by Nogg-aholic** [comment]
this shouldnt rly have something to do with PowerSuit after you removed it but if you send me a Crashlog and some reproduction steps i can look into this ( incase this persists for you in the next update, i probably wont update pre U4 anymore. )
closing this for now, as mentioned pls reopen if this persists on U4 after the next update
