### ISSUE TITLE
Flight Issues in Multiplayer

### ISSUE THREAD

**Issue by Whiskey-Sunshine** [Nogg-aholic/PowerSuit#2]
Current Version: PowerSuit 0.3.1
Satisfactory Version: CL#131382

Issue: Multiplayer using the flight is not working correctly on the host side. Other players connecting to the host using identical modules/suits have no problems.

Details: The speed boost function of the flight is not working correctly for the host. The top speed is limited to 5 m/s, but continues to use fuel at the boosted rates when using the booster. Modules that increase flight speed do not change the maximum speed. Other players that connect (and use the same suit and modules, both made by them or made by the host and given to them) have the proper effects and speeds when flying and boosting.

Other Information: We removed other mods and re-added them one at a time during testing to see if any of them were causing some kind of conflict, but the issue persisted even when it was just PowerSuit and PowerSuit Modules. The issue was also present when using PowerSuit_NogsDefaultModules to unlock flight in place of PowerSuit Modules.

If you need any more information from me, let me know and I will supply whatever you need. I also greatly appreciate the groundwork that this mod provides, thank you for your time and effort in creating it!

**Comment by Whiskey-Sunshine** [comment]
Update: A simple issue that I missed, turns out that it is fixed entirely by turning on vsync. My fps before using vsync was usually around 90-110, keeping it at 60 seems to clear up all the issues.

**Comment by Nogg-aholic** [comment]
Thanks for the Error Report and the Update !
Yes, i assumed already it was related to the FPS relation to speeds. I have a Fix ready for that which will be deployed with the next Update. I will leave this issue open untill its release.

**Comment by Nogg-aholic** [comment]
Fixed alot of FPS related Speed functions, the only thing that is still tied to FPS somehow is Z Velocity which should now be higher the lower your FPS is ( capped somewhere around 30 ), so upwards Thrust "should" always work. 
Please re-open this if there are more issues tied to FPS and Speeds aside from the described Z beheavior.
