### ISSUE TITLE
client sided power generation issues

### ISSUE THREAD

**Issue by lancce-Wolf** [Nogg-aholic/PowerSuit#23]
as a client suit power generators that use / need items to produce suit power wont work at all.
only passive generating power modules like the bioloop generator and the radiation absorbing generator work, probably the uranium decay generator will work as well but i havent got that far yet.

had issues with the following power generation modules as a client (they worked fine as host)

> Bio reactor module
> Fuel reactor module
> Slug Amplification Generator
(couldnt test the other ones yet)

after some more testing it seems like they actually do generate power for the host so you can continue flying while the suit shuts off and reboots but as a client it gets buggy since the host says "everything is fine you shouldnt fall down and just continue like nothing is wrong with your suit" even though on the clients side it says no power and its rebooting the suit because of that.
<img width="1904" alt="Screenshot 2021-08-30 035310" src="https://user-images.githubusercontent.com/37783216/131274667-f24da2a3-0c76-4df3-9091-8d825653cc27.png">

**Comment by budak7273** [comment]
This is a problem in PowerSuit Modules and not PowerSuit itself, so I'm looking into it on my end. 

If you have a slug amp generator equipped, it currently confuses the suit, as the list of valid slug items is not set up correctly on clients, so the power gen does not come over correctly.

Do you still have issues with the item-consuming power gen modules even when the slug module is not installed? In my testing, they only bug out when the slug generator is installed too.

**Comment by lancce-Wolf** [comment]
yea can confirm, i have no issues with item-consuming generators anymore no matter if i have the slug module installed or not which is weird. the fuel generator modules also show now that they produce power
<img width="1920" alt="Screenshot 2021-09-01 012812" src="https://user-images.githubusercontent.com/37783216/131588570-b6b4f9b2-0b11-4023-bdc4-1a052a03f928.png">

**Comment by lancce-Wolf** [comment]
okay i had to remove the slug power module again because it bugged out the other generators again. was just standing afk in the game as client. removing it instantly fixed the other generators.

**Comment by budak7273** [comment]
This has been fixed internally and will be released soon. Contact me on Discord if you would like early release that has the fix.

**Comment by lancce-Wolf** [comment]
we will wait for the official release. i will close this once i tested it and found it working.

**Comment by budak7273** [comment]
This should be fixed as of tonight's release.

**Comment by lancce-Wolf** [comment]
was finally able to try it out and can confirm it works as inteded now.
thank you very much and have a nice day.
