### ISSUE TITLE
Hand slot upgrade did not hand slot

### ISSUE THREAD

**Issue by MxtressMyxx** [Nogg-aholic/PowerSuit#26]
In a recent save, we unlocked MkII Suits. The inventory upgrade worked, but the additional hand slot did not apply.

Before the upgrade, we had 5 hand slots unlocked - no other mods are adding hand slots. No sixth slot is added.

I can post both our save (right before the unlock) and SMM profile if that helps.

Is there a way to manually apply the hand slot to fix this?

**Comment by budak7273** [comment]
Thanks for the report!

Hmm, that is quite unusual. I just tried to cause it to happen in-game with nothing else unlocked (fresh game with skip tutorial, the SetNextGamePhase cheat to advance elevator phases, and the GiveActiveMilestoneSchematic cheat after picking them in the HUB) and the extra hand slots unlocked just fine.

The way I award hand slots is the normal base-game way, so I don't think the mod is at fault here. Are able to cause it reliably on your end?

Go ahead and send the before and after save files and the SMM profile, I might be able to look into it further later.

In the mean time, you should be able to edit hand slot count with SatisfactorySaveEditor. Follow the guide [here](https://ficsit.app/guide/Z8h6z2CczH43c) to install it, then use File> Jump to Tag and enter `Persistent_Level:PersistentLevel.UnlockSubsystem`, then edit it in the right pane.

**Comment by MxtressMyxx** [comment]
[before-after-smm_profile.zip](https://github.com/Nogg-aholic/PowerSuit/files/7260318/before-after-smm_profile.zip)
Here you go!
I'll give the save editor a try.

**Comment by budak7273** [comment]
Closing since the issue was probably not with the mod, and no longer occurs on newer versions
