### ISSUE TITLE
Update 5 compatibility?

### ISSUE THREAD

**Issue by Pomax** [Nogg-aholic/PowerSuit#27]
SMM still lists powersuit as questionably compatible now that Update 5 landed, would it be possible to push out a new release that's compatible with the current game?

**Comment by budak7273** [comment]
Hello,

As it states at the top of the [mod page](https://ficsit.app/mod/7J2LyFzTakqPQ5) :

> An Update 5 compatible version is in progress, you can get early releases on the Nog's Mods Discord Server

You can join here: http://discord.gg/zqp6U7Y7Nu

**Comment by Pomax** [comment]
Ah, I didn't see that in SMM. I don't use discord, but thank you for the reply.
