### ISSUE TITLE
powersuit

### ISSUE THREAD

**Issue by saucyminx** [Nogg-aholic/PowerSuit#29]
I've downloaded the mod plus the modules that are to go with it.
the issue im having is that the craftable power-suit mk I (only tier i have unlocked) isn't appearing in the craft bench or equipment bench, but all the modules and research in the M.E.M are fully working.
Im using update 5 so would that be the issue or would it be something else?
im not currently using any other mods

**Comment by budak7273** [comment]
For future readers, questions like this can usually be answered by the [mod page](https://ficsit.app/mod/BezrE8aswqXLRX).
