### ISSUE TITLE
in multiplayer the suit looks like a hover pack

### ISSUE THREAD

**Issue by neonyxiaa** [Nogg-aholic/PowerSuit#30]
basically for my friend my bio power suit looks like a hover pack

**Comment by budak7273** [comment]
![image](https://user-images.githubusercontent.com/25965766/164992045-f41c6a6a-cb73-47f1-8a6c-fec6de2b5b01.png)

Thanks for the report. This is a known bug (see screenshot). All suits look like hover packs, but for some reason the color of the host's suit does not display correctly.

**Comment by budak7273** [comment]
Fixed in 1.0.0
