### ISSUE TITLE
Equipment Inventory not opening on "Right-Alt"

### ISSUE THREAD

**Issue by Sh4kE** [Nogg-aholic/PowerSuit#4]
Hi,
unfortunatly the Equipment Inventory does not show up on my game.

I'm playing on Linux with steam/proton on the beta branch with a german keyboard layout.
I have equipped the MKI Powersuit and those two bars are showing up normally.

Game Version: Early Access CL#138516
Mod Loader Version: v2.2.1
Bootstrapper Version: v2.0.11
PowerSuit Version: 0.3.2
PowerSuit Modules Version: 1.2.0

**Comment by Sh4kE** [comment]
I guess this is not a fault of your mod but rather from Satisfactory itself. When I temporarily set my keyboard layout to us it works like a charm.

I am also unable to open up the console with a qwertz layout in vanilla Satisfactory. So I guess I need to wait until CoffeeStain ficses it.

**Comment by Nogg-aholic** [comment]
Hey, thanks for the Bug Report ! 
Not the Next Update but with the next SML Update, Keys should be setable via Config, at which point, my own choosing of HotKeys wont matter anymore as much. in the Meantime, i could only change it globally and that is always a difficult decision. Hoping for a soon arrival of the Update.

**Comment by budak7273** [comment]
Closing this issue as it was resolved by the SML3 update which brought SML keybinding support.
