### ISSUE TITLE
Flight Sounds Not Respecting Game Audio Settings

### ISSUE THREAD

**Issue by patrick-hill** [Nogg-aholic/PowerSuit#5]
First off, many thanks for the great work on this mod and the recent update is looking awesome!
I'm having an issue with the flight sounds being far too loud regardless of what options I'm setting in the games audio settings.

Let me know if any configs/screen shots would help troubleshoot this. Thanks in advance

**Comment by budak7273** [comment]
The jetpack's sounds do not currently obey the volume sliders. This will be fixed in the next update; it will be on the 'effects' slider (and it will listen to the master one too).

**Comment by budak7273** [comment]
This was implemented in 0.4.1, but I forgot to comment here about it when that was released.
