### ISSUE TITLE
Vertical Thrust buggy

### ISSUE THREAD

**Issue by DomKue** [Nogg-aholic/PowerSuit#6]
Using current CL#138887, my equiped Power Suit Mk3 with three modules (INtegrated Blade Runners Module, Hover Jetpack Module, Sprinting Compensator Mk1 Module) works kinda strange: From time to time, I cannot rise any more, but I go down when pressing space. After stop flighing, sometime it works again, sometimes it takes some random movements or so - could not make a scheme for that.

**Comment by Miranina** [comment]
I noticed that bug as well but I'm unsure if it's the same behaviour for you. A workaround for me is to simply "unload" the graphic engine by looking at the floor. It seems that in my case when the GPU is badly overloaded (below 30 fps on a 1070 ... yeah huge factory) the mod don't register the space pressed fast enough.

**Comment by budak7273** [comment]
Closing this issue as it was resolved by the SML3 update, which changed all flight to use the base game's Hoverpack flight system, replacing the previous flight system entirely.
