### ISSUE TITLE
Cannot jump without triggering jetpack

### ISSUE THREAD

**Issue by WorstGirl** [Nogg-aholic/PowerSuit#8]
Experimental CL#139586
PowerSuit 0.4.1, Modules 2.0.3

With either the hover or vanilla jetpack modules equipped, any attempt to jump will trigger the jetpack.
Prior to 0.4.1 it worked correctly, only activating when held briefly.

Video example: https://files.catbox.moe/5995l7.mp4

**Comment by budak7273** [comment]
Thanks for the report!

I left this change in on accident, and it has been fixed in the update that just came out today, along with some extra config options. More details are in the patch notes.
